# Generated by Django 4.2.9 on 2024-04-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="doctor_photos"),
        ),
    ]
