# Generated by Django 4.2.9 on 2024-04-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pdp", "0002_article_alter_doctorprofile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="pdp.category",
            ),
        ),
    ]
