# Generated by Django 4.2.9 on 2024-04-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdp", "0005_post_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="category", new_name="category_name",
        ),
    ]
