# Generated by Django 4.2.9 on 2024-04-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdp", "0007_rename_category_name_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("1", "General"),
                    ("2", "Internal medicine"),
                    ("3", "Surgical"),
                    ("4", "Stomatology"),
                    ("5", "Dermatology"),
                    ("6", "Obstetrics and Gynecology"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
