# Generated by Django 4.2.9 on 2024-04-02 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pdp", "0008_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default="None",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default="General",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pdp.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(default="Empty article"),
        ),
    ]
